- hosts: webservers
  tasks:
    - name: Check yum location
      stat:
          path: /usr/bin/yum
      register: yum_path

    - name: Check git location
      stat:
         path: /usr/bin/git
      register: git_path

    - name: Install git in linux node
      yum:
          name: git
          state: present
          update_cache: yes
      when: yum_path.stat.exists == True and git_path.stat.exists == False

    - name: Install git in ubuntu  node
      apt:
          name: git
          state: present
          update_cache: yes
      when: yum_path.stat.exists == False and git_path.stat.exists == False


    - debug:
          msg: 'Already git is installed'
      when: git_path.stat.exists == True

