- hosts: localhost
  tasks:
  - name: create
    docker_container:
            name: webappcontainer
            image: klogambigai/stackdemo:latest
            state: present
            recreate: yes
            ports:
            - 8000:5000
    tags: create

  - name: Start container with healthstatus
    docker_container:
            name: webappcontainer
            image: klogambigai/stackdemo:latest
            state: started
            links:
            - redis:redis
            ports:
            - 8000:8000
            healthcheck:
            # Check if nginx server is healthy by curl'ing the server.
            # If this fails or timeouts, the healthcheck fails.
              test: ["CMD", "curl", "--fail", "http://localhost:8000/"]

    tags: healthcheck

  - name: remove
    docker_container:
            name: webappcontainer
            image: klogambigai/stackdemo:latest
            state: absent
            recreate: yes
            exposed_ports:
            - 8000:5000
    tags: remove
