---
- hosts: localhost


  vars:
   -  db_user: app1user
   -  db_password: app1user
   -  db_name: app1

  pre_tasks:
    - name: "Install packages"
      yum: "name={{ pkg }} state=present"

      vars:
        pkg:
        - postgresql
        - postgresql-server
