---
- hosts: localhost
  tasks:
  - name: Check current docker-compose version
    command: docker-compose --version
    register: doccompose_vsn

  - name: Install python3-pip
    yum:
        name: python3-pip
        state: present

  - name: Install docker-compose
    pip:
        name:
         - docker
         - docker-compose
        executable: pip-3.7

  - debug:
       msg: "{{ doccompose_vsn.stdout }}"
