---
- hosts: localhost
  tasks:
  - name: Install python-pip
    yum:
         name: python-pip
         state: present
  - name: Install boto3 module
    pip:
         name: boto3
         state: present
  - name: read password and print from aws secreet
    debug:
      msg: " {{ lookup('aws_secret','dev/app/postgrespwd') }}"
