---
- hosts: localhost
  vars:
    #token: 's.msZM0ZYpACy30kNoCnNtlWiS'
    password_vault: "{{ lookup('hashi_vault', 'secret=/kv/dev/app/psqlpwd token=s.msZM0ZYpACy30kNoCnNtlWiS url=http://34.238.251.19:8200 validate_certs=false') }}"
  tasks:
  - name: Install python-pip
    yum:
         name: python-pip
         state: present
  - name: Install hvac module
    pip:
         name: hvac

  - name: read password and print from aws secreet
    debug:
      # first one wont work failed in look,dont change kv and it should be like that
      #msg: "{{ lookup('hashi_vault', 'secret=/psql/dev/app/psqlpwd token=s.msZM0ZYpACy30kNoCnNtlWiS url=http://34.238.251.19:8200 validate_certs=false') }}"
      #msg: "{{ lookup('hashi_vault', 'secret=/kv/dev/app/psqlpwd token=s.msZM0ZYpACy30kNoCnNtlWiS url=http://34.238.251.19:8200 validate_certs=false') }}"
      msg: "{{ password_vault }}"
