---
- hosts: webservers
  vars:
    tomcat_url: https://downloads.apache.org/tomcat/tomcat-8/v8.5.61/bin/apache-tomcat-8.5.61.tar.gz 
    tomcat_download_directory: /opt
    tomcat_download_version: apache-tomcat-8.5.61
  tasks:
    - name: Java installation
      yum:
           name: java-1.8.0-openjdk
           state: present
    - name: Install tomcat
      get_url:
           url:  "{{ tomcat_url }}"
           dest: /opt
           mode: '0440'
    - name: Unarchive tomcat tar
      unarchive:
           src: "{{ tomcat_download_directory }}" / "{{ tomcat_download_version }}"
           dest: /opt
           remote_src: yes
 
    - name: Tomcat service copy
      copy:
          src: ./tomcat.service.j2
          dest: /etc/systemd/system
          mode: 0777
       
    - name: Tomcat service copy
      copy:
          src: ./tomcat.service
          dest: /etc/systemd/system
          mode: 0777
    - name: Start the tomcat
      service:
          name: tomcat
          state: started
