---
- hosts: localhost
  #vars:
  # - postgres_pwd: Password1
  vars_files:
    - password.yml
  tasks:
  - name: Run db container
    docker_container:
      name: psql-container
      image: postgres:v1
      state: started
      recreate: yes
      ports:
      - 5432:5432
      env:
        PGUSER: flaskdb
        POSTGRES_PASSWORD: "{{ postgres_pwd }}"

    tags: create

  - name: Remove db container
    docker_container:
      name: psql-container
      image: postgres:v1
      state: absent
      recreate: yes
    tags: remove

